from model.environment.functional_models.f2.six_vessel_interactions_f2 import six_vessel_interactions
from model.environment.functional_models.f2.five_vessel_interactions_f2 import five_vessel_interactions
from model.environment.functional_models.f2.four_vessel_interactions_f2 import four_vessel_interactions
from model.environment.functional_models.f2.three_vessel_interactions_f2 import three_vessel_interactions