from model.environment.functional_models.f1.six_vessel_interactions_f1 import six_vessel_interactions
from model.environment.functional_models.f1.five_vessel_interactions_f1 import five_vessel_interactions
from model.environment.functional_models.f1.four_vessel_interactions_f1 import four_vessel_interactions
from model.environment.functional_models.f1.three_vessel_interactions_f1 import three_vessel_interactions