services:
  TS_3_arduagent:
    command: python -B -u /app/main.py
    depends_on:
    - TS_3_mavproxy
    - TS_3_simulator
    environment: &id001
    - NAME=TS_3
    - DOMAIN=surface
    - REAL_SIM=simulation
    - AGENT_DESCRIPTION=surface vessel
    - AGENT_MODEL=vessel.mini_usv
    - VIDEO_SRC0=/dev/video0
    - VIDEO_SERVER=ome.waraps.org
    - BROKER=host.docker.internal
    - PORT=1883
    - TLS_CERTIFICE=0
    - MQTT_USER=
    - MQTT_PASSWORD=
    - FCS_SERIAL=/dev/serial0
    - BAUD_RATE=57600
    - CONNECTION_STRING=tcp:TS_3_mavproxy:14551
    - SIM_PORT=5760
    - SPEEDUP=1
    - VEHICLE=Rover
    - MODEL=rover-skid
    - VEHICLE_PARAMS=Rover
    - INSTANCE=0
    - HOME_POS=55.66300321099707,17.369728554371235,0,179.40496399067837
    - MAVPROXY=tcpin:TS_3_mavproxy:14551
    - LOCAL_BRIDGE=udp:localhost:14550
    - GCS_1=udp:host.docker.internal:14555
    image: registry.waraps.org/waraps-arduagent:test
    restart: unless-stopped
  TS_3_mavproxy:
    command: mavproxy.py --master=tcp:TS_3_simulator:5760 --out=tcpin:TS_3_mavproxy:14551
      --out=udp:host.docker.internal:14555
    depends_on:
    - TS_3_simulator
    environment: *id001
    image: registry.waraps.org/waraps-mavproxy:latest
    restart: unless-stopped
    stdin_open: true
    tty: true
  TS_3_simulator:
    environment: *id001
    image: registry.waraps.org/ardupilot-sitl:test
    restart: unless-stopped
    volumes:
    - C:\Users\freyd\Desktop\USVLogicSceneGeneration\src\utils/../../assets/simulation/gen/params-4vessel_0obstacle_ts_3.params:/params/myRover.params
