services:
  TS_2_arduagent:
    command: python -B -u /app/main.py
    depends_on:
    - TS_2_mavproxy
    - TS_2_simulator
    environment: &id001
    - NAME=TS_2
    - DOMAIN=surface
    - REAL_SIM=simulation
    - AGENT_DESCRIPTION=surface vessel
    - AGENT_MODEL=vessel.mini_usv
    - VIDEO_SRC0=/dev/video0
    - VIDEO_SERVER=ome.waraps.org
    - BROKER=host.docker.internal
    - PORT=1883
    - TLS_CERTIFICE=0
    - MQTT_USER=
    - MQTT_PASSWORD=
    - FCS_SERIAL=/dev/serial0
    - BAUD_RATE=57600
    - CONNECTION_STRING=tcp:TS_2_mavproxy:14551
    - SIM_PORT=5760
    - SPEEDUP=1
    - VEHICLE=Rover
    - MODEL=rover-skid
    - VEHICLE_PARAMS=Rover
    - INSTANCE=0
    - HOME_POS=454.3695190438467,536.8344457864596,0,26.27995799516367
    - MAVPROXY=tcpin:TS_2_mavproxy:14551
    - LOCAL_BRIDGE=udp:localhost:14550
    - GCS_1=udp:host.docker.internal:14554
    image: registry.waraps.org/waraps-arduagent:test
    restart: unless-stopped
  TS_2_mavproxy:
    command: mavproxy.py --master=tcp:TS_2_simulator:5760 --out=tcpin:TS_2_mavproxy:14551
      --out=udp:host.docker.internal:14554
    depends_on:
    - TS_2_simulator
    environment: *id001
    image: registry.waraps.org/waraps-mavproxy:latest
    restart: unless-stopped
    stdin_open: true
    tty: true
  TS_2_simulator:
    command: /ardupilot/Tools/autotest/sim_vehicle.py --vehicle Rover --frame rover-skid
      -I0 --custom-location="454.3695190438467,536.8344457864596,0,26.27995799516367"
      -w --no-rebuild --no-mavproxy --speedup 1
    environment: *id001
    image: registry.waraps.org/ardupilot-sitl:test
    restart: unless-stopped
    volumes:
    - C:\Users\freyd\Desktop\USVLogicSceneGeneration\src\utils/../../assets/simulation/gen/params-4vessel_0obstacle_ts_2.params:/params/myRover.params
